### ISSUE TITLE
syntax protection for non returning fn calls

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/gtclang#14]
The code below should not be legal, 
there is one error printed, but a bit confusing

`
 note: candidate stencil function not viable: requires 2 arguments, but 1 was provided
`

```
stencil_function TestFun {
  storage in;
  storage out;

  Do() {
      out = in;
  }
};

stencil Test {
  storage field_a, field_b;

  Do {
    vertical_region(k_start, k_end) {
      field_a = field_b;
      TestFun(field_a, field_b) = field_b;
    }
  }
};
```

**Comment by thfabian** [comment]
I think the error is completely wrong and just by chance related to the stencil function. I think this can be adressed by deleting the assignment operator of `gridtools::clang::stencil_function` (I haven't tested it though). Otherwise we need to this in the parser.

**Comment by cosunae** [comment]
ok, thanks. I have a more fundamental question. Now we can have exactly the same error in the SIR (protobuf) since we dont know if the frontend DSL is implementing these checks. Otherwise in dawn we can simply get wrong results or nasty bugs. 
That is what I meant with running consistency checks of the messages of the SIR. Now, are we gonna implement the same checks at the level of gtclang and SIR? shall we move those in gtclang related to properly form stencils from gtclang to SIR? Shall we duplicate most of them?

**Comment by thfabian** [comment]
My few cents on the problem. I would argue that if a certain pass in Dawn assumes a certain language construct it is the responsibility of the pass itself to enfore it’s validity. For example, for the code above I would argue the inlining pass should still run fine (the generated C++ code is invalid of course). Imho it should in general be the responsibility of the frontend to generate sane SIR code as it is very difficult to check everything. That being said, we could have a consistency pass which runs on the SIR and does the most obvious checks. I think the same strategy is used in Clang/LLVM (Clang will always generate sane IR but LLVM does some checks)

**Comment by cosunae** [comment]
thanks for the thoughts. I agree that if dawn does already include checks, then is not required at the level of the SIR... But is gonna be difficult to have a 100% coverage, to know when something does not require check at the SIR. On the other hand, if we really want to open the SIR to users, I really think we need to protect it, specially with the google protobuffers scheme there is very little protection. You can always argue that is responsibility of the user, but the API, i.e. is gonna be quite complex, so if the frontend is not perfect, it is gonna be very hard for them to plug into our stuff if an error generates internal seg faults or issues in dawn. 

Do you know details on how it is done in llvm?

https://llvm.org/docs/LangRef.html#well-formedness
