### ISSUE TITLE
(from clang-gridtools #29) make_independent for Stages

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/gtclang#30]
Insert `make_independent`  when applicable in the code generation for gridtools

**Comment by Stagno** [comment]
@twicki 
I read from current GridTools documentation that the purpose of `make_independent` is to let 2 stages run in parallel.
```
If two stages have no dependencies, they don’t need to be synchronized. Thus, the user can make them independent.
```
But in dawn such stages would be merged together, right?
I don't know GridTools codegen enough to tell whether this matters or not.

**Comment by twicki** [comment]
Basically we don't need it since we can always fuse these stages. Make independent is just that in the GridTools world.
